### PR TITLE
Use `random_bytes` instead of `openssl_random_pseudo_bytes` if available

### PR DESCRIPTION
**Pull request by fetus-hina**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | none

Note: CI is failing, but it isn't my scope.

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Please add a line for https://github.com/yiisoft/yii2-composer/blob/master/CHANGELOG.md

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Comment by samdark** [comment]
Do you need it in the release or is it an enhancement you can live without for some time?

**Comment by fetus-hina** [comment]
I **don't** think a release is required immediately.

**Pull request merged**
