### PR TITLE
Remove tests section from PR template

### PR DESCRIPTION
**Pull request by rob006**
There is no tests in this repo, there is no sense to have this section in PR template.

### CODE REVIEW

**Comment by rob006** [comment]
BTW: I don't see the point of this section in other repositories to - tests (if available) are handled by the CI, why duplicate this information in issue comment?

**Comment by samdark** [comment]
The main goal is to get more attention to the fact that tests have a huge influence on the speed and outcome of PR reviews.

**Comment by samdark** [comment]
In this case you're absolutely correct. Thanks!

**Comment by rob006** [comment]
> The main goal is to get more attention to the fact that tests have a huge influence on the speed and outcome of PR reviews.

Right now it looks like you expect to run test locally before opening PR (in many cases only then I will know if test are OK) or simply guess. If you only want gets more attention to test, maybe its better to change this section to something like "Covered by tests?" - it suggests writing test for new features and fixes, which has more sense than suggesting run tests locally before opening PR.

**Comment by samdark** [comment]
Well, running tests locally won't hurt...

**Comment by rob006** [comment]
... only wasting your time by doing something that is already done automatically. :) I guess that spending this time to write new tests will be more useful for project.

**Comment by cebe** [comment]
to write proper tests you need to run them locally...

**Comment by rob006** [comment]
You can create PR and wait for CI results. And then push another fixes until CI will be green.

**Comment by samdark** [comment]
OK. I have no objections to renaming it to "has tests".

**Pull request merged**
